apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicaSet
  type: front-end
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
       - name: nginx-container
         image: nginx
         resources:
          limits:
            cpu: 500m
            memory: 100Mi
  replicas: 3
  selector: 
    matchLabels:
      type: front-end