---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pv-pod
  name: pv-pod
  namespace: auth
spec:
  containers:
  - image: busybox
    name: pv-pod
    resources: {}
    command:
    - "sh"
    - "-c"
    - "while true; do echo success > /output/output.log; sleep 5; done"
    volumeMounts:
    - name: host-storage-pvc
      mountPath: /output
  volumes:
  - name: host-storage-pvc
    persistentVolumeClaim:
      claimName: host-storage-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-storage-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-storage-pvc
  namespace: auth
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
