apiVersion: v1
kind: Pod
metadata:
  labels:
    run: logging-sidecar
  name: logging-sidecar
  namespace: baz
spec:
  containers:
  - image: busybox
    name: logging-sidecar
    command:
    - "sh"
    - "-c"
    - "while true; do echo Logging data > /output/output.log; sleep 5; done"
    volumeMounts:
    - name: localvol
      mountPath: /output
    resources: {}
  - image: busybox
    name: sidecar
    command:
    - "sh"
    - "-c"
    - "tail -f /output/output.log"
    resources: {}
    volumeMounts:
    - name: localvol
      mountPath: /output
  volumes:
  - name: localvol
    emptyDir: {}