apiVersion: v1
kind: ConfigMap
metadata:
  name: mixed-config-map
  annotations:
    kubernetes.io/description: "You can even write a description to this so ppl knwo what's going on"
data:
  username: admin
  some.conf: |
    name: 
      this: "name"
    some: key
    this can be anything!! 
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-password-secret
type: Opaque
data:
  password: UG9sc2thMTIz # Has to be Base64 encoded
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-and-cm
  labels:
    example: secret-configmap
spec:
  volumes:
  - name: config-mount
    configMap:
      name: mixed-config-map
      items:
      - key: some.conf
        path: some.conf
  containers:
  - name: myapp
    image: nginx:alpine
    env:
    - name: USERNAME
      valueFrom:
        configMapKeyRef: 
          name: mixed-config-map 
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: simple-password-secret
          key: password
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: config-mount
      mountPath: /data/configuration
      readOnly: true

