apiVersion: v1
kind: ConfigMap
metadata:
  name: mixed-config-map
  annotations:
    kubernetes.io/description: "You can even write a description to this so ppl knwo what's going on"
data:
  username: admin
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello Webpage</title>
    <style>
      body {
        font-family: 'Pacifico', cursive;
        background-color: #aee7dc; /* Pastel turquoise */
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
      }

      .hello-text {
        font-size: 24px;
        color: #333; /* Dark grey */
      }
    </style>
    </head>
    <body>
      <div class="hello-text">Hello on my webpage</div>
    </body>
    </html>
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-password-secret
type: Opaque
data:
  password: UG9sc2thMTIz # Has to be Base64 encoded
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-and-cm
  labels:
    example: secret-configmap
spec:
  volumes:
  - name: config-mount
    configMap:
      name: mixed-config-map
      items:
      - key: index.html
        path: index.html
  containers:
  - name: myapp
    image: nginx:alpine
    env:
    - name: USERNAME
      valueFrom:
        configMapKeyRef: 
          name: mixed-config-map 
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: simple-password-secret
          key: password
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: config-mount
      mountPath: /usr/share/nginx/html
      readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: expose-nginx
spec:
  type: NodePort
  selector:
    example: secret-configmap
  ports:
  - port: 80
    targetPort: 80