apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  # namespace: dev 

spec: 
  type: LoadBalancer
  ports:
    - targetPort: 80    # POD port
      port: 80          # Service Port
      nodePort: 30005   # Node Port
  selector:
    app: myapp
    type: front-end